/*! \file
 * AUTOGENERATED FILE, DO NOT EDIT, see src/debugflags.def instead.
 * Enumerate debug flags and their short description
 */

cout << "\tprint_step\t:\tprint each step as it is being executed\n";
cout << "\tneibs\t:\tdebug the neighbors list on host\n";
cout << "\tforces\t:\tdebug forces on host\n";
cout << "\tnumerical_density\t:\tdebug relative density variation on host\n";
cout << "\tinspect_preforce\t:\tinspect pre-force particle status\n";
cout << "\tinspect_pregamma\t:\tinspect pre-gamma integration particle status\n";
cout << "\tinspect_buffer_access\t:\tinspect buffer access\n";
cout << "\tinspect_buffer_lists\t:\tinspect buffer lists at the end of each command\n";
cout << "\tcheck_buffer_update\t:\tcheck buffer update\n";
cout << "\tcheck_buffer_consistency\t:\tcheck buffer consistency\n";
cout << "\tclobber_invalid_buffers\t:\tclobber invalid buffers\n";
cout << "\tvalidate_init_positions\t:\tThrow (instead of just warn) if a particle is out of bounds during init\n";
cout << "\tbenchmark_command_runtimes\t:\tMeasure (and show) command runtimes\n";
